In [3]:
import geopandas as gpd
import pandas as pd

In [5]:
oferta = pd.read_csv(r"E:\SPTrans\pedido 096412- oferta\Partidas.csv")
oferta

          Unnamed: 0  Ano Mês Tipo Dia    Linha  Sentido  Vira Horario
0                  6   202212     UTIL  1012-10        1     0   05:00
1                  8   202212     UTIL  1012-10        1     0   05:12
2                  9   202212     UTIL  1012-10        1     0   05:24
3                 10   202212     UTIL  1012-10        1     0   05:36
4                 11   202212     UTIL  1012-10        1     0   05:48
...              ...      ...      ...      ...      ...   ...     ...
12972443      353632   202512     DOMG  N843-11        1     0   01:20
12972444      353633   202512     DOMG  N843-11        1     0   02:00
12972445      353634   202512     DOMG  N843-11        1     0   02:40
12972446      353635   202512     DOMG  N843-11        1     0   03:20
12972447      353636   202512     DOMG  N843-11        1     0   04:00

[12972448 rows x 7 columns]

In [11]:
oferta["Ano"] = oferta["Ano Mês"].astype(str).str[:4]
oferta["Mês"] = oferta["Ano Mês"].astype(str).str[-2:]
oferta

,Unnamed: 0,Ano Mês,Tipo Dia,Linha,Sentido,Vira,Horario,Ano,Mês
0,6,202212,UTIL,1012-10,1,0,05:00,2022,12
1,8,202212,UTIL,1012-10,1,0,05:12,2022,12
2,9,202212,UTIL,1012-10,1,0,05:24,2022,12
3,10,202212,UTIL,1012-10,1,0,05:36,2022,12
4,11,202212,UTIL,1012-10,1,0,05:48,2022,12
...,...,...,...,...,...,...,...,...,...
12972443,353632,202512,DOMG,N843-11,1,0,01:20,2025,12
12972444,353633,202512,DOMG,N843-11,1,0,02:00,2025,12
12972445,353634,202512,DOMG,N843-11,1,0,02:40,2025,12
12972446,353635,202512,DOMG,N843-11,1,0,03:20,2025,12
12972447,353636,202512,DOMG,N843-11,1,0,04:00,2025,12